// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHv7sCp5wmuX7pp2OIvqQ7gFoPsOkof64',
    appId: '1:968183926365:web:d8ce55acf0b3abbc2c47b4',
    messagingSenderId: '968183926365',
    projectId: 'profe-7f791',
    authDomain: 'profe-7f791.firebaseapp.com',
    storageBucket: 'profe-7f791.firebasestorage.app',
    measurementId: 'G-SZCWN12DMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnstFaiVNTnJyQEj0g8a0PJNL40eMuFKs',
    appId: '1:968183926365:android:82fa12264706c9132c47b4',
    messagingSenderId: '968183926365',
    projectId: 'profe-7f791',
    storageBucket: 'profe-7f791.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy6sZWq1Y5-w5hFzLeP4LO_t6bhvfKr0o',
    appId: '1:968183926365:ios:57e136de3c6a330f2c47b4',
    messagingSenderId: '968183926365',
    projectId: 'profe-7f791',
    storageBucket: 'profe-7f791.firebasestorage.app',
    iosBundleId: 'com.example.programaProfe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy6sZWq1Y5-w5hFzLeP4LO_t6bhvfKr0o',
    appId: '1:968183926365:ios:57e136de3c6a330f2c47b4',
    messagingSenderId: '968183926365',
    projectId: 'profe-7f791',
    storageBucket: 'profe-7f791.firebasestorage.app',
    iosBundleId: 'com.example.programaProfe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHv7sCp5wmuX7pp2OIvqQ7gFoPsOkof64',
    appId: '1:968183926365:web:5833546a12c1b33d2c47b4',
    messagingSenderId: '968183926365',
    projectId: 'profe-7f791',
    authDomain: 'profe-7f791.firebaseapp.com',
    storageBucket: 'profe-7f791.firebasestorage.app',
    measurementId: 'G-L2VTKV94B2',
  );
}
